[build]
  Functions = "functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/smashing"
  status = 302

[[redirects]]
  from = "/draw"
  to = "/smashing/draw"
  status = 302

[[redirects]]
  from = "/when"
  to = "https://smashingconf.com/"
  status = 200
